# Site settings
title: Afif Al hawari
header-img: img/home-bg.jpg
email: afif.alhawari@gmail.com
description: "Story of my life"
url: "http://afifalhawari.com"
twitter_username: afifalhawari
github_username:  afifalhawari
linkedin_username: afifalhawari

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
